sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
before_script:
  - pip install pep8==1.6.2
script:
  - python setup.py test
  - pep8 blockfinder block_finder/ setup.py
