sudo: false
language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
before_script:
  - pip install pycodestyle
  - pip install Click
script:
  - python setup.py test
  - pycodestyle blockfinder block_finder/ setup.py
